name: Export file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt update
        sudo apt install cargo
        cargo install monolith
        monolith https://garv-shah.github.io/EducationPerfected/settings/ -o output.html
        mv output.html output.txt
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        # Artifact name
        name: settings
        # Destination path
        path: output.txt
    
