name: Export file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt update
        sudo apt install cargo
        cargo install monolith
        monolith https://garv-shah.github.io/EducationPerfected/settings/ -o output.html
        git clone https://github.com/KEN-2000l/EducationPerfected.git
        rm -rf EducationPerfected/output.txt
        mv output.html EducationPerfected/output.txt
        cd EducationPerfected
        git add .
        git commit -m "Automatically Updated Website"
        git push origin main
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: settings
        path: output.txt
